version: '3'

services:
  db:
    image: 'mongo'
    container_name: 'DB-CONTROLE-ESTOQUE'
    ports:
      - '27017:27017'
    # "Linkando" os dados locais com os do container
    volumes:
      - './data/db:/data/db'

  server:
    container_name: 'SERVER-CONTROLE-ESTOQUE'
    # Fazendo build no Dockerfile do folder root
    build: '.'
    # O primeiro item é responsável por atualizar os itens locais com o do
    # container sem a necessidade de reiniciar/buildar o container a cada
    # alteracao no codigo.
    # #################################
    # O Segundo item permite a sincronizacao dos 'pacotes' locais com o do
    # container.
    volumes:
      - './:/node-app/'
      - './node_modules:/node-app/node_modules'
    # O serviço 'server' depende do serviço 'db' para funcionar
    depends_on:
      - db
    ports:
      - '9000:9000'

  web:
    container_name: 'WEB-CONTROLE-ESTOQUE'
    build: './client'
    volumes:
      - './client/:/web-app/'
      - './client/node_modules:/web-app/node_modules'
    depends_on:
      - server
    ports:
      - '3000:3000'

volumes:
  node_modules:
